name: MavenHomework3

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout project sources
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Downloading UA Client
        run: |
          echo "Downloading the UA"
          curl -LJ "https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar" -o "UA.jar"

      - name: Verifying the UA scanner
        run: |
          echo "Verifying the UA"
          java -jar "UA.jar" -v
      
      - name: Downloading CLI Client
        run: |
          echo "Downloading the CLI"
          curl "https://downloads.mend.io/cli/linux_amd64/mend" -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend
     
      - name: Verify Scanner
        run: |
          echo "Verifying the CLI"
          mend version
      
      - name: Scan with UA
        env:
          WS_MAVEN_RUNPRESTEP: true
          WS_MAVEN_RESOLVEDEPENDENCIES: true
          WS_APIKEY: ${{ secrets.APIKEY }}
          WS_USERKEY: ${{ secrets.MEND_USER_KEY }}
          WS_WSS_URL: ${{ secrets.WS_WSS_URL }}
          WS_PRODUCTNAME: OSSTestUA
          WS_PROJECTNAME: UAWebGoat
          WS_LOG_LEVEL: DEBUG
        run: java -jar UA.jar

      - name: Build Maven for CLI
        run: mvn clean install -DskipTests

      - name: Scan with CLI
        env:
          MEND_URL: ${{ secrets.MEND_URL }}
          MEND_USER_KEY: ${{ secrets.MEND_USER_KEY }}
          MEND_EMAIL: ${{ secrets.MEND_EMAIL}}
          MEND_LOG_LEVEL: DEBUG
        run: |
          mend dep --update --scope "OSSTestCLI//CLIWebGoat" --non-interactive -e
        continue-on-error: true
      
      - name: Printing CLI logs
        run: cat ~/.mend/logs/sca/*
      
